SELECT * FROM HR.COURSE_UNITS INNER JOIN HR.UNITS ON HR.COURSE_UNITS.UNIT_ID = HR.UNITS.UNIT_ID GROUP BY HR.COURSE_UNITS.COURSE_ID;

SELECT UNIT_ID FROM HR.UNITS;

SELECT * FROM HR.UNITS ORDER BY HR.UNITS.UNITS_ID ASC;

SELECT * FROM HR.PAYMENT ORDER BY HR.PAYMENT.Pay_Date DESC;

SELECT * FROM HR.PAYMENT WHERE HR.PAYMENT.STUDENT_ID = HR.STUDENT.STUDENT_ID ORDER BY HR.PAYMENT.Pay_Date DESC;

SELECT * FROM HR.REGISTER_UNITS WHERE HR.REGISTER_UNITS.STUDENT_ID = HR.STUDENT.STUDENT_ID HR.INNER JOIN UNITS ON HR.REGISTER_UNITS.UNIT_ID = HR.UNITS.UNIT_ID

SELECT * FROM HR.LEC_UNITS WHERE INNER JOIN HR.UNITS ON HR.UNITS.UNIT_ID = HR.LEC_UNITS.UNIT_ID INNER JOIN HR.LECTURES.STAFF_ID = HR.LEC_UNITS.STAFF_ID

SELECT * FROM HR.PAYMENT WHERE HR.PAYMENT.PAY_DATE >= '2021/5/1' AND HR.PAYMENT.PAY_DATE <= '2021/6/1'

